import constants from "./config/constants.js";
const { BASE_URL_WITHOUT_API_DOC } = constants;

let i = 1;

const apiDoc = [{},
{
    new_tag: '0',
    color: 'blue',
    icon: 'http',
    title: 'DIRECT LINK',
    name: 'ABOUT US',
    meth: 'Link',
    link: BASE_URL_WITHOUT_API_DOC + "cms/about_us",
    imp: "ABOUT US",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'http',
    title: 'DIRECT LINK',
    name: 'PRIVACY POLICY',
    meth: 'Link',
    link: BASE_URL_WITHOUT_API_DOC + "cms/privacy_policy",
    imp: "PRIVACY POLICY",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'http',
    title: 'DIRECT LINK',
    name: 'TERMS & CONDITION',
    meth: 'Link',
    link: BASE_URL_WITHOUT_API_DOC + "cms/terms_condition",
    imp: "TERMS & CONDITION",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'http',
    title: 'DIRECT LINK',
    name: 'FAQ',
    meth: 'Link',
    link: BASE_URL_WITHOUT_API_DOC + "cms/faq",
    imp: "FAQ",
},
{},
{
    new_tag: '1',
    color: 'green',
    title: 'ENC/DEC API',
    icon: 'key',
},
{
    new_tag: '0',
    color: 'red',
    icon: 'lock',
    title: i++ + ' : ENCYPTION',
    name: 'ENCYPTION',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "enc_dec/local/encryption",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This api is used to encrypte data",
    example: '',
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'lock',
    title: i++ + ' : DECRYPTION',
    name: 'DECRYPTION',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "enc_dec/local/decryption",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This api is used to decrypt data",
    example: '',
    status: "",
    imp: "",
},
{},
{
    new_tag: '2',
    color: 'black',
    title: 'COMMON API',
    icon: 'list',
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'lock',
    title: i++ + ' : COMMON',
    name: 'GET CREDENTIAL',
    meth: 'GET',
    link: BASE_URL_WITHOUT_API_DOC + "common/credential_details",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This api is used to get credential",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'flag',
    title: i++ + ' : COMMON',
    name: 'Get Country List',
    meth: 'GET',
    link: BASE_URL_WITHOUT_API_DOC + "common/country_list",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This api is used to get country list",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : COMMON',
    name: 'Get Notification List',
    meth: 'GET',
    link: BASE_URL_WITHOUT_API_DOC + "common/notification_list",
    mandatory: "page",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This api is used to get notification list",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "Per page 10 data <br> In notification_tag key type like 'add_task' for task notification, 'add_document' for upload document, 'admin_notification' for Admin notification",
},
{},
{
    new_tag: '3',
    color: 'red',
    title: 'AUTH API',
    icon: 'person',
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'SIGN UP',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/signup",
    mandatory: "role(company/client), first_name, last_name, email, country_code, mobile_number, password, login_type(S/F/G/A), device_type(A/I/W), device_token",
    optional: "social_id, uuid, ip, os_version, model_name, device_name, language, referral_code, voip_token",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This Api is used to user Sign Up",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "If company signup then passed role='company' and if client signup then passed role='client' <br> If signup with fecbook then passed login_type='F' <br> If signup with google then passed login_type='G' <br> If signup with apple then passed login_type='A' <br> If simpale signup then passed login_type='S'",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'COMPLETE PROFILE',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/complete_profile",
    mandatory: "role(company/client/employee), user_name, description, profile_image, device_type(A/I/W), device_token",
    optional: "address, latitude, longitude, company_id, organization_id, uuid, ip, os_version, model_name, device_name, language, voip_token",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to user complete profile",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 22 <br>4. HTTP_OK[200] - code : 33 <br>5. HTTP_OK[200] - code : 44 ",
    imp: "If company then passed role='company' and if client then passed role='client' and if employee then passed role='employee' <br> If role='company' then if code 22 come then document screen if code 33 come then add organization screen if code 44 then subscription screen",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'UPLOAD DOCUMENT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/upload_document",
    mandatory: "role(company), license, id_proof, device_type(A/I/W), device_token",
    optional: "uuid, ip, os_version, model_name, device_name, language, voip_token",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to user upload document",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 33 <br>4. HTTP_OK[200] - code : 44 ",
    imp: "If company then passed role='company' and if client then passed role='client' and if employee then passed role='employee' <br> If role='company' then if code 33 come then add organization screen if code 44 then subscription screen",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'ADD ORGANIZATION',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/add_organization",
    mandatory: "role(company), organization_name, organization_site, organization_location, device_type(A/I/W), device_token",
    optional: "uuid, ip, os_version, model_name, device_name, language, latitude, longitude, voip_token",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add organization",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 44 ",
    imp: "If company then passed role='company' and if client then passed role='client' and if employee then passed role='employee' <br> If role='company' then if code 44 then subscription screen",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'LOGIN',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/login",
    mandatory: "role(company/employee/client), email, device_type(A/I/W), device_token",
    optional: "password, social_id, uuid, ip, os_version, model_name, device_name, language, voip_token",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to login",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 11 <br>4. HTTP_OK[200] - code : 22 <br>5. HTTP_OK[200] - code : 33 <br>6. HTTP_OK[200] - code : 44 ",
    imp: "If company then passed role='company' and if client then passed role='client' and if employee then passed role='employee' <br> If role='company' then if code 11 come then complete profile screen if code 22 come then document screen if code 33 come then add organization screen if code 44 then subscription screen <br> If Code 55 come then social_id is not register",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'RESEND OTP',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/resend_otp",
    mandatory: "role(company/client), user_id",
    optional: "type(E)",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This Api is used to resend otp",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "If profile edit and mobile number change then passed type='E'",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'VERIFY OTP',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/verify_otp",
    mandatory: "role(company/client), user_id, otp",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This Api is used to verify otp",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'FORGOT PASSWORD',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/forgot_password",
    mandatory: "role(company/client/employee), email",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This Api is used to forgot password",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'CHANGE PASSWORD',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/change_password",
    mandatory: "current_password, new_password, confirm_password",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to change password",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'DELETE ACCOUNT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/delete_account",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to delete account",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'LOGOUT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/logout",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to logout",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'CONTACT US',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/contact_us",
    mandatory: "subject, email, description",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to contact us",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'USER DETAILS',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/user_details",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to user details",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'EDIT PROFILE',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/edit_profile",
    mandatory: "",
    optional: "user_name, first_name, last_name, email, country_code, mobile_number, profile_image, description, license, id_proof, client_organization",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to edit profile",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1",
    imp: "In client_organization give as array in this array passed company_id, organization_id, is_default, is_active, is_delete in object for multiple organization",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : AUTH',
    name: 'UPDATE DEVICE INFO',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/update_device_info",
    mandatory: "device_type(A/I/W), device_token",
    optional: "uuid, ip, os_version, model_name, device_name, language, voip_token",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to update device info",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'list',
    title: i++ + ' : AUTH',
    name: 'ORGANIZATION LIST FOR CLIENT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/organization_list_for_client",
    mandatory: "",
    optional: "type('company')",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get organization list for client",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "If organization_id!='0' then passed type='company'",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'list',
    title: i++ + ' : AUTH',
    name: 'ADD OR EDIT NOTIFICATION PREFERNCES',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/add_or_edit_notification_prefernces",
    mandatory: "is_task_notification, is_task_email, is_lead_notification, is_lead_email, is_event_notification, is_event_email",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add or edit notification prefernces",
    example: '{ is_task_notification: false, is_task_email: false, is_lead_notification: false, is_lead_email: false, is_event_notification: false, is_event_email: false }',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{},
{
    new_tag: '4',
    color: 'blue',
    title: 'SUBSCRIPTION API',
    icon: 'money',
},
{
    new_tag: '0',
    color: 'gray',
    icon: 'add',
    title: i++ + ' : SUBSCRIPTION',
    name: 'SUBSCRIPTION PURCHASE',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "subscription/subscription_purchase",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to purchase subscription",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{},
{
    new_tag: '5',
    color: 'navy',
    title: 'ORGANIZATION API',
    icon: 'company',
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'person',
    title: i++ + ' : ORGANIZATION',
    name: 'ORGANIZATION LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "organization/organization_list",
    mandatory: "",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get organization list",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'person',
    title: i++ + ' : ORGANIZATION',
    name: 'ADD ORGANIZATION',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "organization/add_organization",
    mandatory: "organization_name, organization_site, organization_location, latitude, longitude",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add organization",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'person',
    title: i++ + ' : ORGANIZATION',
    name: 'EDIT ORGANIZATION',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "organization/edit_organization",
    mandatory: "organization_id",
    optional: "organization_name, organization_site, organization_location, is_default, is_active, is_delete, latitude, longitude",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to edit organization",
    example: '{"organization_id":"2","organization_name":"Test 2","organization_site":"http://test.com","organization_location":"23 test"}',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "If any organization select as default then passed is_default=true <br>If organization block then passed is_active=false <br>If organization delete then passed is_delete=true",
},
{},
{
    new_tag: '6',
    color: 'red',
    title: 'MEMBER API',
    icon: 'person',
},
{
    new_tag: '0',
    color: 'brown',
    icon: 'person',
    title: i++ + ' : MEMBER',
    name: 'TOTAL MEMBERS LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "member/total_members_list",
    mandatory: "organization_id, page",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to total members of organization",
    example: '',
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "Per page 8 data",
},
{
    new_tag: '0',
    color: 'brown',
    icon: 'person',
    title: i++ + ' : MEMBER',
    name: 'ADD MEMBER',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "member/add_member",
    mandatory: "organization_id, first_name, last_name, country_code, mobile_number, email, member_rights",
    optional: "team_id",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add member of organization and team",
    example: `{"team_id":"1","organization_id":"1","first_name":"test","last_name":"tessttss","country_code":"+91","mobile_number":"98989836123","email":"tirthghyperlinkinfosystem.net.in@gmail.com","member_rights":[{"type":"Tasks","is_add":"0","is_update":"1","is_view":"1","is_delete":"0"},{"type":"Leads","is_add":"0","is_update":"1","is_view":"1","is_delete":"0"},{"type":"Teams","is_add":"0","is_update":"1","is_view":"1","is_delete":"0"},{"type":"Organization","is_add":"0","is_update":"1","is_view":"1","is_delete":"0"}]}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "In member_rights give array and in this array passed type,is_add,is_update,is_view,is_delete key in object",
},
{
    new_tag: '0',
    color: 'brown',
    icon: 'person',
    title: i++ + ' : MEMBER',
    name: 'EDIT MEMBER',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "member/edit_member",
    mandatory: "employee_id",
    optional: "team_id, organization_id, first_name, last_name, country_code, mobile_number, email, is_company_block, is_company_delete, member_rights",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to edit member of organization and team",
    example: `{"employee_id":"1","team_id":"1","organization_id":"1","first_name":"test","last_name":"tessttss","country_code":"+91","mobile_number":"98989836123","email":"tirthghyperlinkinfosystem.net.in@gmail.com","member_rights":[{"type":"Tasks","is_add":"0","is_update":"1","is_view":"1","is_delete":"0"},{"type":"Leads","is_add":"0","is_update":"1","is_view":"1","is_delete":"0"},{"type":"Teams","is_add":"0","is_update":"1","is_view":"1","is_delete":"0"},{"type":"Organization","is_add":"0","is_update":"1","is_view":"1","is_delete":"0"}]}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "In member_rights give array and in this array passed type,is_add,is_update,is_view,is_delete key in object <br>If you delete member then passed is_company_delete=true <br>If you block member then passed is_company_block=true",
},
{
    new_tag: '0',
    color: 'brown',
    icon: 'person',
    title: i++ + ' : MEMBER',
    name: 'MEMBER DETAILS',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "member/member_details",
    mandatory: "employee_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get member details",
    example: `{"employee_id":"1"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'brown',
    icon: 'person',
    title: i++ + ' : MEMBER',
    name: 'SELECT MEMBER LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "member/select_members_list",
    mandatory: "organization_id",
    optional: "search, team_id",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get select member list",
    example: `{"organization_id":"1","team_id":"1","search":"test"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "If select team member list then passed team_id",
},
{
    new_tag: '0',
    color: 'brown',
    icon: 'person',
    title: i++ + ' : MEMBER',
    name: 'CLIENT LIST FOR MEMBER',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "member/total_client_list_for_member",
    mandatory: "company_id,organization_id,page",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get client list for member",
    example: `{"company_id":"1","organization_id":"1","page":"1","search":"test"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2",
    imp: "",
},
{},
{
    new_tag: '7',
    color: 'green',
    title: 'TEAM API',
    icon: 'person',
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'person',
    title: i++ + ' : TEAM',
    name: 'MY TEAMS LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "team/my_teams",
    mandatory: "organization_id, page",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get my team list",
    example: `{"organization_id":"1"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "Per page 8 data",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'person',
    title: i++ + ' : TEAM',
    name: 'MY TEAMS PIN LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "team/my_teams_pin_list",
    mandatory: "organization_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get my team pin list",
    example: `{"organization_id":"1"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'person',
    title: i++ + ' : TEAM',
    name: 'CREATE TEAM',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "team/create_team",
    mandatory: "organization_id, team_name, team_profile_image, employee_ids, background_color",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to create team",
    example: `{"organization_id":"1","team_name":"Team Test","team_profile_image":"test.jpg","employee_ids":["1","2","4","5","14"]},"background_color":"#000000"`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "In employee_ids passed array of employee_id",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'person',
    title: i++ + ' : TEAM',
    name: 'TEAM DETAILS',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "team/team_details",
    mandatory: "team_id, page",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get team details",
    example: `{"team_id":"6"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "Per page 8 data",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'person',
    title: i++ + ' : TEAM',
    name: 'SELECT TEAM MEMBER',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "team/select_member",
    mandatory: "team_id, employee_ids",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to select team member",
    example: `{"team_id":"6","employee_ids":["1",2,14]}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'person',
    title: i++ + ' : TEAM',
    name: 'EDIT TEAM',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "team/edit_team",
    mandatory: "team_id",
    optional: "team_name, team_profile_image, employee_ids, is_active, is_delete, is_pin,background_color",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to edit team",
    example: `{"team_id":"1","team_name":"Team Test","team_profile_image":"test.jpg","employee_ids":["1","2","4","5","14"],"is_active":"true","is_delete":"false","is_pin":"true","background_color":"#000000"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "In employee_ids passed array of employee_id",
},
{},
{
    new_tag: '8',
    color: 'black',
    title: 'HOME API',
    icon: 'home',
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'person',
    title: i++ + ' : HOME',
    name: 'TOTAL COUNTS',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "home/total_counts",
    mandatory: "organization_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get home total counts",
    example: `{"organization_id":"1"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'person',
    title: i++ + ' : HOME',
    name: 'CURRENT TASK LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "home/current_task_list",
    mandatory: "organization_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get current task list",
    example: `{"organization_id":"1"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'person',
    title: i++ + ' : HOME',
    name: 'UPCOMING MEETING LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "home/upcoming_meeting_list",
    mandatory: "company_id, organization_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get upcoming meeting list",
    example: `{"company_id":"1","organization_id":"2"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{},
{
    new_tag: '9',
    color: 'green',
    title: 'CLIENT API',
    icon: 'client',
},
{
    new_tag: '0',
    color: 'red',
    icon: 'list',
    title: i++ + ' : CLIENT',
    name: 'MY CLIENT LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "client/my_client_list",
    mandatory: "organization_id, page",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get my client list",
    example: `{"organization_id":"1","page":"1"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "Per page 10 data",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'person',
    title: i++ + ' : CLIENT',
    name: 'ADD CLIENT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "client/add_client",
    mandatory: "organization_id, email, first_name, last_name, country_code, mobile_number",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add client",
    example: `{"organization_id":"1","email":"tirthg@yopmail.com","first_name":"Test","last_name":"test","country_code":"+91","mobile_number":"8721215245"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'person',
    title: i++ + ' : CLIENT',
    name: 'CLIENT DETAILS',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "client/client_details",
    mandatory: "client_id, client_organization_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get client details",
    example: `{"client_id":"2"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'person',
    title: i++ + ' : CLIENT',
    name: 'EDIT CLIENT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "client/edit_client",
    mandatory: "client_id",
    optional: "email, first_name, last_name, country_code, mobile_number, is_active, is_delete",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add client",
    example: `{"client_id":"3","email":"tirthtest@yopmail.com","first_name":"Test","last_name":"test","country_code":"+91","mobile_number":"8721215265"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'person',
    title: i++ + ' : CLIENT',
    name: 'ADD DOCUMENT FOR CLIENT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "client/add_document",
    mandatory: "organization_id, document_title, pdf",
    optional: "document_description, pdf_thumbnail, client_id, company_id",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add document for client",
    example: `{"organization_id":"2","client_id":"3","document_title":"NDA","document_description":"This is test document upload","pdf":"123.pdf"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "If Company side api call then client_id passed <br> If Client side api call then company_id passed",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'person',
    title: i++ + ' : CLIENT',
    name: 'DOCUMENT LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "client/documents_list",
    mandatory: "organization_id, type(upload_by_you / upload_by_client)",
    optional: "client_id",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get document list for client",
    example: `{"organization_id":"2","client_id":"3","type":"upload_by_you"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "If Company side api call then client_id passed",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'person',
    title: i++ + ' : CLIENT',
    name: 'EDIT DOCUMENT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "client/edit_document",
    mandatory: "document_id",
    optional: "document_title, document_description, pdf, is_active, is_delete, pdf_thumbnail",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to edit document",
    example: `{"document_id":"1","document_title":"NDA","document_description":"This is test document upload","pdf":"456.pdf"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{},
{
    new_tag: '10',
    color: 'purple',
    title: 'TASK API',
    icon: 'task',
},
{
    new_tag: '0',
    color: 'green',
    icon: 'add',
    title: i++ + ' : TASK',
    name: 'ADD TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/add_task",
    mandatory: "organization_id, client_id, team_ids, employee_ids, task_name, start_date, start_time, end_date, end_time, task_priority, description",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add task",
    example: `{"client_id":"3","organization_id":"2","team_ids":[2],"employee_ids":[2,4],"task_name":"Test","start_date":"2024-05-26","start_time":"11:50 Am","end_date":"2024-05-28","end_time":"11:12 Pm","task_priority":"High","description":"tttttttttt"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'list',
    title: i++ + ' : TASK',
    name: 'TASK LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/task_list",
    mandatory: "organization_id",
    optional: "search, type(create_by_you / create_by_other), team_id, employee_ids",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get task list",
    example: `{"organization_id":"2","employee_ids":[1,2,3],"team_id":"1","type":"create_by_you"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'add',
    title: i++ + ' : TASK',
    name: 'TASK PROGRESS CHANGE',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/task_progress_change",
    mandatory: "task_id",
    optional: "task_progress('in_progress'/'open'/'completed')",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to change task progress",
    example: `{"task_id":"2","task_progress":"open"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'list',
    title: i++ + ' : TASK',
    name: 'CLIENT LIST FOR ADD TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/client_list_for_add_task",
    mandatory: "organization_id",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get client list for add task",
    example: `{"organization_id":"2"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'list',
    title: i++ + ' : TASK',
    name: 'TEAM LIST FOR ADD TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/team_list_for_add_task",
    mandatory: "organization_id",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get team list for add task",
    example: `{"organization_id":"2"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'list',
    title: i++ + ' : TASK',
    name: 'EMPLOYEE LIST TEAM WISE FOR ADD TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/employee_list_team_wise",
    mandatory: "organization_id, team_ids",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get employee list team wise for add task",
    example: `{"organization_id":"2","team_ids":[20]}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : TASK',
    name: 'TASK DETAILS',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/task_details",
    mandatory: "task_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get task details",
    example: `{"task_id":"2"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : TASK',
    name: 'ADD MEDIA OR DOCUMENT FOR TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/add_media",
    mandatory: "task_id, type(media/document)",
    optional: "file_array:[file,file_type(image/video)], file_type(pdf), file_name, file, pdf_thumbnail",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add media or document for task",
    example: `{"task_id":"2","type":"media","file_array":[{"file":"test.png","file_type":"image"},{"file":"test.mp4","file_type":"video"}]}                     {"task_id":"1","file_name":"adfsd","file":"156465656156.pdf","file_type":"pdf","pdf_thumbnail":"ksahjdnsf.jpg"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "If type='document' then passed file_type, file_name, file, pdf_thumbnail <br>If type='media' then passed file_array in this array passed file and file_type in object",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : TASK',
    name: 'GET MEDIA OR DOCUMENT LIST FOR TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/media_or_document_list",
    mandatory: "task_id, type(media/document)",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get media or document list for task",
    example: `{"task_id":"2","type":"media"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : TASK',
    name: 'ADD COMMENT FOR TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/add_comment",
    mandatory: "task_id, comment",
    optional: "pdf_data",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to add comment for task",
    example: `{"task_id":"2","comment":"test comment","pdf_data":[{"document_name":"first.pdf","pdf":"pdfname.pdf","thumbnail":"thumbnail.png","file_type":"pdf"}]}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "If pdf_data passed document_name, pdf, thumbnail, file_type(pdf/image/video) in array object",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'list',
    title: i++ + ' : TASK',
    name: 'GET COMMENT LIST FOR TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/comment_list",
    mandatory: "task_id",
    optional: "type='page', page",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to get comment list for task",
    example: `{"task_id":"2","type":"page","page":1}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "Per page 10 data",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'person',
    title: i++ + ' : TASK',
    name: 'EDIT TASK',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "task/edit_task",
    mandatory: "task_id",
    optional: "client_id, team_ids, employee_ids, task_name, start_date, start_time, end_date, end_time, description, is_active, is_delete, is_lock",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This Api is used to edit task",
    example: `{"task_id":"2"}`,
    status: "<br>1. HTTP_OK[200] - code : 0 <br>2. HTTP_OK[200] - code : 1 <br>3. HTTP_OK[200] - code : 2 ",
    imp: "",
},
{},
{
    new_tag: '11',
    color: 'red',
    title: 'VIDEO/VOICE API',
    icon: 'video',
},
{
    new_tag: '0',
    color: 'green',
    icon: 'video',
    title: i++ + ' : VIDEO/VOICE',
    name: 'VIDEO/VOICE CALL TOKEN GENERATE',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/video_voice_call_token",
    mandatory: "userId,call_type(S/G)",
    optional: "channel_name, group_name",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to create call token",
    example: `{ "userId": "3", "call_type":"G", "channel_name": "sjb","group_name":"sssss" }`,
    status: "",
    imp: "IF call_type='G' then passed group_name",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'video',
    title: i++ + ' : VIDEO/VOICE',
    name: 'JOINED CALL USER LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/get_call_user_list",
    mandatory: "agora_uids",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get call user list",
    example: `{ "agora_uids": ["10066","200645","30054","1003"] }`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'video',
    title: i++ + ' : VIDEO/VOICE',
    name: 'CALL START',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/call_start",
    mandatory: "agora_uids,chat_room_id,type(video/voice),call_type(S/G), channel_name",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to start call",
    example: `{ "agora_uids": ["10066"],"chat_room_id":"1","type":"S","call_type":"S" }`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'video',
    title: i++ + ' : VIDEO/VOICE',
    name: 'CALL STATUS UPDATE',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/call_status_update",
    mandatory: "call_history_id, type(call_received/call_end/call_missed/call_declined)",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to update call status",
    example: `{ "agora_uids": ["10066"],"chat_room_id":"1","type":"S","call_type":"S" }`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'video',
    title: i++ + ' : VIDEO/VOICE',
    name: 'GET CALL HISTORY',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/get_call_history",
    mandatory: "page",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get call history list",
    example: `{ "page": "1" }`,
    status: "",
    imp: "Per page 10 data",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'detailed',
    title: i++ + ' : VIDEO/VOICE',
    name: 'GET USER DETAILED BY AGORA UID',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "auth/user_details_by_agora_uid",
    mandatory: "agora_uid",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get user detailed by agora uid",
    example: `{ "agora_uid": "1005" }`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'detailed',
    title: i++ + ' : VIDEO/VOICE',
    name: 'CHECK CALL START OR NOT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/check_call_start_or_not",
    mandatory: "chat_room_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to check call start or not",
    example: `{ "chat_room_id": 2 }`,
    status: "",
    imp: "If call start then data get and if call not start then code 2 get and data null",
},
{
    new_tag: '0',
    color: 'green',
    icon: 'detailed',
    title: i++ + ' : VIDEO/VOICE',
    name: 'CHECK CALL START OR NOT WITH AGORA UID',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/check_call_start_or_not_with_agora_id",
    mandatory: "agora_uid",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to check call start or not with agora uid",
    example: `{ "agora_uid": '20025' }`,
    status: "",
    imp: "If call start then data get and if call not start then code 2 get and data null",
},
{},
{
    new_tag: '12',
    color: 'blue',
    title: 'CHAT API',
    icon: 'chat',
},
{
    new_tag: '0',
    color: 'red',
    icon: 'chat',
    title: i++ + ' : CHAT',
    name: 'CREATE CHAT ROOM',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/create_chat",
    mandatory: "receiver_id,receiver_type",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to create chat room",
    example: `{ "receiver_id": "3", "receiver_type": "employee" }`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'list',
    title: i++ + ' : CHAT',
    name: 'CHAT HISTORY',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/chat_history",
    mandatory: "chat_room_id,page",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This api is used to get chat room history",
    example: `{ "chat_room_id": "1","page": "1" }`,
    status: "",
    imp: "Per page 10 data show",
},
{
    new_tag: '0',
    color: 'red',
    icon: 'list',
    title: i++ + ' : CHAT',
    name: 'CHAT USER LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/chat_user_list",
    mandatory: "page",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY",
    notes: "This api is used to get chat room history",
    example: `{ "page": "1" }`,
    status: "",
    imp: "Per page 10 data show",
},
{},
{
    new_tag: '13',
    color: 'green',
    title: 'GROUP CHAT API',
    icon: 'chat',
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'CREATE GROUP CHAT ROOM',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/create_group_chat",
    mandatory: "organization_id, group_name, group_description, is_private(true/false), members([{user_id, user_type(company,client,employee), role(admin,simple)}])",
    optional: "group_image",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to create group chat room",
    example: `{"organization_id":"1","group_name":"Test","group_image":"test.jpg","group_description":"Lorem ipsum dolor sit.","is_private":true,"members":[{"user_id":"2","user_type":"employee","role":"admin"},{"user_id":"3","user_type":"employee","role":"simple"}]}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'GROUP LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/group_list",
    mandatory: "type(E,M), page, organization_id",
    optional: "search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get group list",
    example: `{"type":"E","page":"1","organization_id":"1"}`,
    status: "",
    imp: "If you see Exploree tab then passed type='E' <br/>If you see My Group tab then passed type='M'",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'GROUP DETAILED',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/group_detailed",
    mandatory: "chat_room_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get group detailed",
    example: `{"chat_room_id":"1"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'GROUP MEMBER REQUEST ACCEPT REJECT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/group_member_request_accept_reject",
    mandatory: "chat_room_id, user_id, user_type(company,client,employee), type(accept,reject)",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to group member request accept reject",
    example: `{"chat_room_id":"1","user_id":"1","user_type":"employee","type":"accept"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'ADD GROUP MEMBER',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/add_group_member",
    mandatory: "chat_room_id, members[{user_id, user_type}]",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to add group member",
    example: `{"chat_room_id":"1","members":[{"user_id":"2","user_type":"employee"},{"user_id":"3","user_type":"employee"}]}`,
    status: ``,
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'MEMBER LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/member_list",
    mandatory: "organization_id, company_id",
    optional: "chat_room_id",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get member list",
    example: `{"chat_room_id":"1","organization_id":"2","company_id":"1"}`,
    status: "",
    imp: "If you create already group and add member then passed chat_room_id",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'LEAVE OR REMOVE GROUP MEMBER',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/leave_or_remove_group_member",
    mandatory: "chat_room_id",
    optional: "user_id, user_type",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to leave or remove group member",
    example: `{"chat_room_id":"1","user_id":"2","user_type":"employee"}`,
    status: "",
    imp: "If you remove another member then passed user_id, user_type",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'delete',
    title: i++ + ' : GROUP CHAT',
    name: 'DELETE GROUP',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/delete_group",
    mandatory: "chat_room_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to delete group",
    example: `{"chat_room_id":"1"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'EDIT GROUP',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/edit_group",
    mandatory: "chat_room_id",
    optional: "group_name, group_image, group_description, is_private(true/false), members([{user_id, user_type(company,client,employee), role(admin,simple)}])",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to edit group",
    example: `{"chat_room_id":"1","group_name":"Test","group_image":"test.jpg","group_description":"Lorem ipsum dolor sit.","is_private":true,"members":[{"user_id":"2","user_type":"employee","role":"admin"},{"user_id":"3","user_type":"employee","role":"simple"}]}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'JOIN GROUP',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/join_group",
    mandatory: "chat_room_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to join group",
    example: `{"chat_room_id":"1"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'teal',
    icon: 'chat',
    title: i++ + ' : GROUP CHAT',
    name: 'MAKE OR REMOVE ADMIN GROUP',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "chat/make_or_remove_admin_group",
    mandatory: "chat_room_id, is_admin(true,false), member_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to make or remove admin group",
    example: `{"chat_room_id":"1","is_admin":true,"member_id":"1"}`,
    status: "",
    imp: "If you set as admin then passed is_admin=true",
},
{},
{
    new_tag: '14',
    color: 'red',
    title: 'MEETING API',
    icon: 'event',
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : MEETING',
    name: 'GET TIMEZONE LIST',
    meth: 'GET',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/timezone_list",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get timezone list",
    example: ``,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : MEETING',
    name: 'GET CANCEL REASON LIST',
    meth: 'GET',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/cancel_reason_list",
    mandatory: "",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get cancel reason list",
    example: ``,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'add',
    title: i++ + ' : MEETING',
    name: 'CREATE MEETING',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/create_meeting",
    mandatory: "company_id, organization_id, client_id, meeting_name, description, start_date, start_time, end_date, end_time, timezone(GMT+5:30), is_video_meeting_link(true/false), meeting_type(one_time / every_weekday / every_week / every_month / every_day), files[{document_type(image / video / doc),document_name,size,file_original_name}], timezone_tzcode('Asia/Kolkata'), public_notes",
    optional: "client_email, client_country_code, client_mobile_number, video_meeting_link, internal_notes, thumbnail_image",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to create meeting",
    example: `{"company_id":"1","organization_id":"2","client_id":"1","meeting_name":"Test","description":"asdsadsad","start_date":"2024-08-17","start_time":"12:05:00","end_date":"2024-09-29","end_time":"22:01:00","timezone":"(GMT+05:30)","meeting_type":"every_month","is_video_meeting_link":false,"timezone_tzcode":"Asia/Kolkata","files":[{"document_type":"image","document_name":"shd.png","size":"5156","file_original_name":"ahaads","thumbnail_image":"aadad.png"}]}`,
    status: "",
    imp: "If is_video_meeting_link=true then passed video_meeting_link <br/>Document and all file upload in 'meeting_document'",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : MEETING',
    name: 'GET MEETING LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/meeting_list",
    mandatory: "organization_id, page, type(in_progress / upcoming / rescheduled / completed / all / cancelled)",
    optional: "company_id, search",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get meeting list",
    example: `{"organization_id":"2","page":"1","type":"all"}`,
    status: "",
    imp: "If user_type=employee/client then passed company_id",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : MEETING',
    name: 'GET MEETING DETAILS',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/meeting_details",
    mandatory: "meeting_type_wise_id, meeting_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get meeting details",
    example: `{"meeting_type_wise_id":"2","meeting_id":"1"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : MEETING',
    name: 'RESCHEDULE MEETING',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/reschedule_meeting",
    mandatory: "meeting_type_wise_id, meeting_id, start_date, start_time, end_date, end_time, timezone, timezone_tzcode, type(all_meetings / only_this), is_video_meeting_link, description, public_notes, meeting_type(one_time / every_weekday / every_week / every_month / every_day), files[{document_type(image / video / doc),document_name,size,file_original_name,thumbnail_image}]",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to reschedule meeting",
    example: `{"meeting_type_wise_id":"2","meeting_id":"1","description":"asdsadsad","start_date":"2024-08-17","start_time":"12:05:00","end_date":"2024-09-29","end_time":"22:01:00","timezone":"(GMT+05:30)","meeting_type":"every_month","is_video_meeting_link":false,"timezone_tzcode":"Asia/Kolkata","files":[{"document_type":"image","document_name":"shd.png","size":"5156","file_original_name":"ahaads","thumbnail_image":"asdsd.png"}]}`,
    status: "",
    imp: "If is_video_meeting_link=true then passed video_meeting_link",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : MEETING',
    name: 'CANCEL MEETING',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/cancel_meeting",
    mandatory: "meeting_type_wise_id, meeting_id, cancel_reason, internal_notes, type(all_meetings / only_this)",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to cancel meeting",
    example: `{"meeting_type_wise_id":"2","meeting_id":"1","cancel_reason":"asdsadsad","internal_notes":"dskjjsd","type":"only_this"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : MEETING',
    name: 'DELETE MEETING',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/delete_meeting",
    mandatory: "meeting_type_wise_id, meeting_id, type(all_meetings / only_this)",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to delete meeting",
    example: `{"meeting_type_wise_id":"2","meeting_id":"1","type":"only_this"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'orange',
    icon: 'list',
    title: i++ + ' : MEETING',
    name: 'EDIT MEETING',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "meeting/edit_meeting",
    mandatory: "meeting_type_wise_id, meeting_id, client_id, meeting_name, start_date, start_time, end_date, end_time, timezone, timezone_tzcode, video_meeting_link, is_video_meeting_link, type(all_meetings / only_this), description, public_notes, meeting_type(one_time / every_weekday / every_week / every_month / every_day)",
    optional: "files[{document_type(image / video / doc),document_name,size,file_original_name,thumbnail_image}]",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to edit meeting",
    example: `{"meeting_type_wise_id":"2","meeting_id":"1","client_id":"1","meeting_name":"sadfsa","description":"asdsadsad","start_date":"2024-08-17","start_time":"12:05:00","end_date":"2024-09-29","end_time":"22:01:00","timezone":"(GMT+05:30)","meeting_type":"every_month","is_video_meeting_link":false,"timezone_tzcode":"Asia/Kolkata","files":[{"document_type":"image","document_name":"shd.png","size":"5156","file_original_name":"ahaads","thumbnail_image":"asdsd.png"}]}`,
    status: "",
    imp: "If is_video_meeting_link=true then passed video_meeting_link",
},
{},
{
    new_tag: '15',
    color: 'green',
    title: 'INVOICE API',
    icon: 'invoice',
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'invoice',
    title: i++ + ' : INVOICE',
    name: 'CREATE INVOICE',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "invoice/create_invoice",
    mandatory: "organization_id, client_id, invoice_due_date, amount, is_send(true/false)",
    optional: "email, country_code, mobile_number, notes",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to create invoice",
    example: `{"organization_id":"2","client_id":"1","invoice_due_date":"2024-08-22","amount":"120","is_send":true,"email":"dfdf@hdsf.sd","country_code":"+91","mobile_number":"5848848488","notes":"45adsfsdfds5fd5sf"}`,
    status: "",
    imp: "If invoice send then is_send=true <br>If invoice save then passed is_send=false",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'list',
    title: i++ + ' : INVOICE',
    name: 'GET INVOICE LIST',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "invoice/invoice_list",
    mandatory: "company_id, organization_id, page, type(unpaid / draft / paid / all)",
    optional: "search, start_date, end_date",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get invoice list",
    example: `{"company_id":"1","organization_id":"2","page":"1","type":"all","start_date":"2024-08-22","end_date":"2024-08-30","search":"sd"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'count',
    title: i++ + ' : INVOICE',
    name: 'GET INVOICE COUNT',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "invoice/invoice_counts",
    mandatory: "company_id, organization_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get invoice count",
    example: `{"company_id":"1","organization_id":"2"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'invoice',
    title: i++ + ' : INVOICE',
    name: 'GET INVOICE DETAILS',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "invoice/invoice_details",
    mandatory: "invoice_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to get invoice details",
    example: `{"invoice_id":"1"}`,
    status: "",
    imp: "",
},
{
    new_tag: '0',
    color: 'blue',
    icon: 'invoice',
    title: i++ + ' : INVOICE',
    name: 'INVOICE SEND',
    meth: 'POST',
    link: BASE_URL_WITHOUT_API_DOC + "invoice/invoice_send",
    mandatory: "invoice_id",
    optional: "",
    is_header: "YES",
    is_push: "NO",
    header: "API-KEY,TOKEN",
    notes: "This api is used to send invoice",
    example: `{"invoice_id":"1"}`,
    status: "",
    imp: "",
},
]

export default apiDoc;